### PR TITLE
Accept the fourth line if and only if it's empty

### PR DESCRIPTION
**Pull request by souzaluuk**
About the issue #13

### CODE REVIEW

**Comment by lubien** [comment]
@souzaluuk You might wanna check the linter.

**Comment by lubien** [comment]
@souzaluuk You may also want to add more unit tests to cover this new edge case.

**Comment by souzaluuk** [comment]
@lubien spacing haha

**Review by lubien — CHANGES_REQUESTED** [review]
Needs unit testing

**Review by lubien — APPROVED** [review]

**Pull request merged**
